/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    LayBadge: typeof import('@layui/layui-vue')['LayBadge']
    LayBreadcrumb: typeof import('@layui/layui-vue')['LayBreadcrumb']
    LayBreadcrumbItem: typeof import('@layui/layui-vue')['LayBreadcrumbItem']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCard: typeof import('@layui/layui-vue')['LayCard']
    LayCheckbox: typeof import('@layui/layui-vue')['LayCheckbox']
    LayDatePicker: typeof import('@layui/layui-vue')['LayDatePicker']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayPage: typeof import('@layui/layui-vue')['LayPage']
    LayRadio: typeof import('@layui/layui-vue')['LayRadio']
    LayRadioGroup: typeof import('@layui/layui-vue')['LayRadioGroup']
    LaySelect: typeof import('@layui/layui-vue')['LaySelect']
    LaySelectOption: typeof import('@layui/layui-vue')['LaySelectOption']
    LaySpace: typeof import('@layui/layui-vue')['LaySpace']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTextarea: typeof import('@layui/layui-vue')['LayTextarea']
    LayTree: typeof import('@layui/layui-vue')['LayTree']
    LvaDialog: typeof import('./../components/LvaDialog/index.vue')['default']
    LvaDrawer: typeof import('./../components/LvaDrawer/index.vue')['default']
    PageTable: typeof import('./../components/PageTable/index.vue')['default']
    PermissionTree: typeof import('./../components/PermissionTree/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/SearchForm/index.vue')['default']
  }
}
